---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: home-sensors
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: ssh://git@github.com/SamuelBagattin/home-sensors.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: home-sensors-grafana-dashboard
  namespace: home-sensors
spec:
  interval: 10m0s
  path: ./kubernetes/grafana-dashboards
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-sensors
    namespace: flux-system
---