apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - opensearch.yaml
  - deliveryhero.yaml
  - prometheus-community.yml
  - bitnami.yaml
  - ingress-nginx.yaml
  - grafana.yaml
  - jetstack.yaml