apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: superset
spec:
  releaseName: superset
  chart:
    spec:
      chart: superset
      sourceRef:
        kind: HelmRepository
        name: superset
        namespace: flux-system
      version: "0.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    ingress:
      ingressClassName: nginx
      enabled: true
      hosts:
        - superset.samuelbagattin.com
      path: /
      pathType: ImplementationSpecific
    redis:
      enabled: true
      master:
        persistence:
          enabled: false
    postgresql:
      enabled: true
      primary:
        persistence:
          enabled: false
