apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trino
spec:
  releaseName: trino
  chart:
    spec:
      chart: trino
      sourceRef:
        kind: HelmRepository
        name: trino
        namespace: flux-system
      version: "x.x.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    ingress:
      ingressClassName: nginx
      enabled: true
      hosts:
        - trino.samuelbagattin.com
      path: /
      pathType: ImplementationSpecific
    redis:
      enabled: true
      master:
        persistence:
          enabled: false
    postgresql:
      enabled: true
      primary:
        persistence:
          enabled: false
