apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opensearch
spec:
  releaseName: opensearch
  chart:
    spec:
      chart: opensearch
      sourceRef:
        kind: HelmRepository
        name: opensearch
        namespace: flux-system
      version: "2.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    replicas: 1
    persistence:
      enabled: false
    resources:
      limits:
        cpu: "1"
        memory: "4Gi"
    initResources:
      limits:
        cpu: "25m"
        memory: "128Mi"
      requests:
        cpu: "25m"
        memory: "128Mi"
    sidecarResources:
      limits:
        cpu: "25m"
        memory: "128Mi"
      requests:
        cpu: "25m"
        memory: "128Mi"
