apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eck-operator
spec:
  releaseName: eck-operator
  chart:
    spec:
      chart: eck-operator
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      version: ">= 8.0.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3