apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: main
spec:
  version: 8.5.3
  nodeSets:
    - name: default
      count: 1
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  cpu: 100m
                  memory: 2Gi
                limits:
                  cpu: 2000m
                  memory: 2Gi
          volumes:
            - name: elasticsearch-data
              emptyDir: { }
      config:
        node.store.allow_mmap: false
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch
  annotations:
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
    - host: elasticsearch.samuelbagattin.com
      http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                  name: main-es-http
                  port:
                   name: https
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  annotations:
    # Enable client certificate authentication
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    # Create the secret containing the trusted ca certificates
    nginx.ingress.kubernetes.io/auth-tls-secret: "monitoring/main-kb-http-certs-public"
    # Specify the verification depth in the client certificates chain
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
spec:
  ingressClassName: nginx
  rules:
    - host: kibana.samuelbagattin.com
      http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                  name: main-kb-http
                  port:
                   name: https
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: main
spec:
  version: 8.5.3
  count: 1
  elasticsearchRef:
    name: main
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: 1Gi
              cpu: 0.1
            limits:
              memory: 2.5Gi
              cpu: 2