apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
spec:
  releaseName: elasticsearch
  chart:
    spec:
      chart: elasticsearch
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      version: ">= 8.0.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    createCert: false
    replicas: 1
    persistence:
      enabled: false
    ingress:
      enabled: true
      className: "nginx"
      pathtype: ImplementationSpecific
      hosts:
        - host: elasticsearch.samuelbagattin.com
          paths:
            - path: /
