apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "35.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    grafana:
      additionalDataSources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-stack.svc.cluster.local:3100
      grafana.ini:
        users:
          viewers_can_edit: false
        auth:
          disable_login_form: false
          disable_signout_menu: false
        auth.anonymous:
          enabled: true
          org_role: Viewer
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
        - grafana.samuelbagattin.com
