apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "39.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    grafana:
      replicas: 1
      deploymentStrategy:
        type: Recreate
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "true"
          multicluster:
            global:
              enabled: false
            etcd:
              enabled: false
          provider:
            allowUiUpdates: true
            foldersFromFilesStructure: true
            updateIntervalSeconds: 30
            disableDelete: false
      persistence:
        enabled: false
      plugins:
        - grafana-clock-panel
        - camptocamp-prometheus-alertmanager-datasource
        - grafana-piechart-panel
        - marcusolsson-json-datasource
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: 'root'
              orgId: 1
              type: file
              updateIntervalSeconds: 10
              disableDeletion: true
              editable: false
              options:
                path: /var/lib/grafana/dashboards

      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://loki-stack.monitoring.svc.cluster.local:3100
            user: ''
            database: ''
            basicAuth: false
            isDefault: false
            jsonData: {}
            readOnly: false
          - name: InfluxDB
            type: influxdb
            access: proxy
            url: http://influxdb2.influxdb2.svc.cluster.local
            user: ''
            database: ''
            basicAuth: false
            isDefault: false
            jsonData:
              defaultBucket: default
              httpMode: POST
              organization: influxdata
              version: Flux
            readOnly: false
            secureJsonData:
              token: XuI0n8CKC5sGdMnfuiGj4A3eNRUaVezcXeEniNzfrbjXkf8fXHgsp7DFjZiLFx6xwFuutvX8al6INJpYn1RRLA==
      grafana.ini:
        users:
          viewers_can_edit: false
        auth:
          disable_login_form: false
          disable_signout_menu: false
        auth.anonymous:
          enabled: true
          org_role: Viewer
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
        - grafana.samuelbagattin.com
