apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - kube-prometheus-stack-release.yaml
  - loki-stack-release.yml
  - grafana-dashboards
  - elasticsearch-release.yaml
  - kibana-release.yaml