apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
  namespace: default
spec:
  initHelper:
    image: "public.ecr.aws/opsterio/busybox:1.27.2-buildx-arm"
  general:
    serviceName: my-first-cluster
    version: 2.4.0
  dashboards:
    enable: true
    version: 2.4.0
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  nodePools:
    - component: masters
      replicas: 1
      diskSize: "5Gi"
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      roles:
        - "data"
        - "master"
      persistence:
        emptyDir: { }