apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
  namespace: default
spec:
  initHelper:
    image: "busybox"
  general:
    serviceName: my-first-cluster
    version: 2.4.0
  dashboards:
    enable: true
    version: 2.4.0
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  nodePools:
    - component: masters
      replicas: 1
      jvm: -Xmx6000M -Xms6000M
      diskSize: "5Gi"
      resources:
        requests:
          memory: "12Gi"
          cpu: "500m"
        limits:
          memory: "12Gi"
          cpu: "500m"
      roles:
        - "data"
        - "master"
      persistence:
        emptyDir: { }