apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opensearch
spec:
  releaseName: opensearch
  chart:
    spec:
      chart: opensearch
      sourceRef:
        kind: HelmRepository
        name: opensearch
        namespace: flux-system
      version: "2.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: opensearch.samuelbagattin.com
      path: /
      hosts:
        - opensearch.samuelbagattin.com
    persistence:
      enabled: false
