apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb2
spec:
  releaseName: influxdb2
  chart:
    spec:
      chart: opensearch-operator
      sourceRef:
        kind: HelmRepository
        name: opensearch-operator
        namespace: flux-system
      version: "2.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 1
  values:
    manager:
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 350Mi
