apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb2
spec:
  storageClassName: ""
  volumeName: influxdb2
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce