apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb2
spec:
  releaseName: influxdb2
  chart:
    spec:
      chart: influxdb2
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
      version: "2.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    resources:
      limits:
        cpu: "512m"
        memory: "4Gi"
    persistence:
      enabled: true
      useExisting: true
      name: influxdb2
      size: "10Gi"
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: influxdb.samuelbagattin.com
