apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
  - release.yml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.crds.yaml