apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
spec:
  releaseName: contour
  chart:
    spec:
      chart: contour
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "7.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: projectcontour/contour
      tag: v1.20.1
    envoy:
      service:
        nodePorts:
          http: 32080
          https: 32443