apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echo
spec:
  releaseName: echo
  chart:
    spec:
      chart: echo-server
      sourceRef:
        kind: HelmRepository
        name: ealenn
        namespace: flux-system
      version: "0.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      hosts:
        - paths:
            - /
          host: echo.samuelbagattin.com
      ingressClassName: nginx
    image:
      tag: latest