apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-problem-detector
spec:
  releaseName: node-problem-detector
  chart:
    spec:
      chart: node-problem-detector
      sourceRef:
        kind: HelmRepository
        name: deliveryhero
        namespace: flux-system
      version: "35.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
